#Tomcat Embedded Server Configuration
server:
  port: 8761
spring:
  application:
    name: eureka-server


#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
